package com.smartbank.dto;

import com.smartbank.enums.AccountType;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * AccountRequest DTO - Data Transfer Object for account creation requests
 * 
 * WHY THIS FILE IS NEEDED:
 * This DTO defines the contract for creating new bank accounts. It separates
 * the API layer from entity classes and provides validation.
 * 
 * WHAT THE CODE DOES:
 * - Contains account type (SAVINGS or CURRENT)
 * - @NotNull validation ensures account type is provided
 * - Used when creating a new account for a user
 * 
 * HOW IT WORKS INTERNALLY:
 * 1. Client sends JSON with account type
 * 2. Spring maps JSON to this DTO
 * 3. Validation ensures account type is provided
 * 4. If valid, passes to service for account creation
 * 5. Service generates unique account number
 * 
 * HOW TO EXPLAIN IN INTERVIEW:
 * "AccountRequest DTO defines the contract for creating bank accounts. It only
 * requires the account type because the account number is auto-generated by the
 * service layer. This ensures unique account numbers across the system. Using
 * a DTO separates the API contract from the entity, providing better security
 * and flexibility. The @NotNull validation ensures the account type is always provided."
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class AccountRequest {

    @NotNull(message = "Account type is required")
    private AccountType accountType;
}
